# Simulation results

- MacOS first run simulated values: 

[346.1388888888888, 363.58333333333326, 369.8888888888889, 391.3750000000001, 409.0416666666668, 420.2916666666667, 422.97222222222206, 455.5555555555555, 502.0833333333333, 546.4444444444443, 578.8194444444445, 695.111111111111, 719.1944444444445, 785.666666666667]
- Linux first run simulated values:

[346.1388888888888, 361.94444444444434, 372.5, 395.5555555555556, 400.5138888888888, 415.4722222222221, 429.7361111111112, 454.18055555555554, 503.1249999999999, 546.1249999999998, 584.8194444444443, 678.402777777778, 730.6944444444441, 784.5833333333333]
- Windows: 
 
 [346.1388888888888, 361.94444444444434, 372.5, 395.5555555555556, 400.5138888888888, 415.4722222222221, 429.7361111111112, 454.18055555555554, 503.1249999999999, 546.1249999999998, 584.8194444444443, 678.402777777778, 730.6944444444441, 784.5833333333333]

In [7]:
# Modifier and sinmulation results for the different platforms

import numpy as np
mod_mac = np.array([2600.0, 2681.5384615384614, 2766.153846153846, 2853.846153846154, 2944.6153846153848, 3038.4615384615386, 3135.3846153846152, 3235.3846153846152, 3338.4615384615386, 3444.6153846153848, 3553.846153846154, 3666.153846153846, 3781.5384615384614, 3900.0])
mac =  np.array([346.1388888888888, 363.58333333333326, 369.8888888888889, 391.3750000000001, 409.0416666666668, 420.2916666666667, 422.97222222222206, 455.5555555555555, 502.0833333333333, 546.4444444444443, 578.8194444444445, 695.111111111111, 719.1944444444445, 785.666666666667])

mod_linux = np.array([2600.0, 2681.5384615384614, 2766.153846153846, 2853.846153846154, 2944.6153846153848, 3038.4615384615386, 3135.3846153846152, 3235.3846153846152, 3338.4615384615386, 3444.6153846153848, 3553.846153846154, 3666.153846153846, 3781.5384615384614, 3900.0])
linux = np.array([346.1388888888888, 361.94444444444434, 372.5, 395.5555555555556, 400.5138888888888, 415.4722222222221, 429.7361111111112, 454.18055555555554, 503.1249999999999, 546.1249999999998, 584.8194444444443, 678.402777777778, 730.6944444444441, 784.5833333333333])

mod_win = np.array([2600.0, 2681.5384615384614, 2766.153846153846, 2853.846153846154, 2944.6153846153848, 3038.4615384615386, 3135.3846153846152, 3235.3846153846152, 3338.4615384615386, 3444.6153846153848, 3553.846153846154, 3666.153846153846, 3781.5384615384614, 3900.0])
win = np.array([346.1388888888888, 361.94444444444434, 372.5, 395.5555555555556, 400.5138888888888, 415.4722222222221, 429.7361111111112, 454.18055555555554, 503.1249999999999, 546.1249999999998, 584.8194444444443, 678.402777777778, 730.6944444444441, 784.5833333333333])

In [2]:
mod_linux - mod_win

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
mod_mac - mod_win

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
mac - linux

array([  0.        ,   1.63888889,  -2.61111111,  -4.18055556,
         8.52777778,   4.81944444,  -6.76388889,   1.375     ,
        -1.04166667,   0.31944444,  -6.        ,  16.70833333,
       -11.5       ,   1.08333333])

In [4]:
mac - win

array([  0.        ,   1.63888889,  -2.61111111,  -4.18055556,
         8.52777778,   4.81944444,  -6.76388889,   1.375     ,
        -1.04166667,   0.31944444,  -6.        ,  16.70833333,
       -11.5       ,   1.08333333])

In [5]:
linux - win

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])